# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updatecoord_f <- function(phi, yy, xx, yx, lambdaupcoord, n2, x, status) {
    .Call('fastfmrlasso_updatecoord_f', PACKAGE = 'fastfmrlasso', phi, yy, xx, yx, lambdaupcoord, n2, x, status)
}

cnloglikprob_f <- function(ncomp, l1normphi, prob, lambda, gamma) {
    .Call('fastfmrlasso_cnloglikprob_f', PACKAGE = 'fastfmrlasso', ncomp, l1normphi, prob, lambda, gamma)
}

fmrlasso_f <- function(x, y, k, lambda, ssdini, exini, gamma = 1, term = 1e-6, maxiter = 1000L, actiter = 10L, warnings = TRUE) {
    .Call('fastfmrlasso_fmrlasso_f', PACKAGE = 'fastfmrlasso', x, y, k, lambda, ssdini, exini, gamma, term, maxiter, actiter, warnings)
}

fmrlassopath_f <- function(x, y, k, lambda, ssdini, exini, gamma = 1, term = 10e-6, maxiter = 1000L, actiter = 10L) {
    .Call('fastfmrlasso_fmrlassopath_f', PACKAGE = 'fastfmrlasso', x, y, k, lambda, ssdini, exini, gamma, term, maxiter, actiter)
}

rcpp_hello_world <- function() {
    .Call('fastfmrlasso_rcpp_hello_world', PACKAGE = 'fastfmrlasso')
}

